<?php

namespace App\Enums;

enum ErrorCodes: string
{
    case TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
    case UNDER_MAINTENANCE = "UNDER_MAINTENANCE";
    case INVALID_SIGNATURE = "INVALID_SIGNATURE";
    case ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND";
    case INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    case VALIDATION_ERROR = "VALIDATION_ERROR";
    case RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
}
